In [ ]:
# list
lst1 = [1,2,3,4,5,6]
lst2 = ['string','another string','yet another']

lst3 = ['string', 1.3, 5, [1, 'second string'], {'John':'34-555-1234'}]

In [ ]:
# lst1:
#     0 -> (type: int, value: 1)
#     1 -> (type:float, value:2.5)
#     ...
#     5 -> 6
    
# lst2:
#     0 -> (type:string, value: 'string')
#     1 -> (type:string, value: 'another string')
#     2 -> 'yet another'
    
# etc.

In [1]:
import numpy as np

In [2]:
a = np.random.random((10,4))
print(a)

[[0.5620709  0.62128501 0.26305827 0.35428766]
 [0.72696287 0.29735172 0.55596014 0.30914644]
 [0.91406693 0.64812887 0.08002297 0.74947274]
 [0.65387601 0.66956472 0.17564937 0.04513991]
 [0.29575139 0.83119685 0.65829961 0.18592188]
 [0.58122643 0.80386593 0.06192248 0.2005585 ]
 [0.19034697 0.27447886 0.78422336 0.53202393]
 [0.43572399 0.64297864 0.00602193 0.94963401]
 [0.08258831 0.44588999 0.52972862 0.74414611]
 [0.47178847 0.40269843 0.77782591 0.11789239]]


In [3]:
print(a.shape)
print(a.size)

(10, 4)
40


In [4]:
b = np.random.random((5,2,3))
print(b)

[[[0.70320889 0.30920052 0.41872349]
  [0.41247428 0.19637921 0.23841517]]

 [[0.31187318 0.76442607 0.81630247]
  [0.96672087 0.98823592 0.12619379]]

 [[0.34456378 0.12450283 0.54616822]
  [0.50302805 0.1330467  0.27245756]]

 [[0.81020379 0.60214098 0.28335608]
  [0.04612902 0.15513025 0.51306905]]

 [[0.17613691 0.50595619 0.55449763]
  [0.65177531 0.36835216 0.13071462]]]


In [6]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.05258385 0.26732953 0.42595702 0.41645595 0.27255633]
   [0.76873933 0.311295   0.76641075 0.37847705 0.7136435 ]
   [0.94506727 0.77180332 0.37738904 0.28475213 0.16249487]
   [0.19225975 0.55569267 0.94581714 0.69336152 0.30841922]]

  [[0.41173143 0.26642636 0.11233432 0.09378045 0.12049557]
   [0.13203844 0.402936   0.25261081 0.24936772 0.7264378 ]
   [0.08978018 0.10474697 0.94546549 0.45811262 0.67327782]
   [0.45744217 0.72421831 0.38330017 0.24237089 0.85993774]]

  [[0.35136216 0.1711816  0.61779336 0.46693344 0.18250477]
   [0.88991468 0.76069565 0.91661767 0.62825501 0.61066905]
   [0.94233294 0.43327816 0.71924688 0.00809677 0.54802603]
   [0.56420008 0.21810158 0.43841356 0.80096374 0.76237367]]]


 [[[0.1303935  0.12033835 0.09277972 0.24209732 0.36187   ]
   [0.1377688  0.8835152  0.57067803 0.87965384 0.74637523]
   [0.99428322 0.65857876 0.15293696 0.02331773 0.12004432]
   [0.92027735 0.36731188 0.85121347 0.45630504 0.4986824 ]]

  [[0.30696219 0.87640186 0.97

In [ ]:
# First row of matrix a
print(a)
print(a[0])

In [ ]:
# First column of matrix a
print(a[:,0])

In [ ]:
# Value in the fifth row and third column of matrix a
print(a[4,2])

In [ ]:
# list equivalent
xlist = [[0.75069265, 0.53100122, 0.48637696, 0.20811268],
 [0.28855746, 0.86233589, 0.82170344, 0.64340505],
 [0.66165029 ,0.66529042 ,0.82118104 ,0.33245214],
 [0.23842237, 0.99227012, 0.70958494, 0.78773342],
 [0.59956754 ,0.72311601 ,0.78621408 ,0.48428124],
 [0.77134511, 0.90509481, 0.39564717, 0.70004292],
 [0.6590291  ,0.28677295 ,0.92953274 ,0.43896178],
 [0.22973736, 0.96647811, 0.51706048, 0.11653039],
 [0.27601849 ,0.7595283  ,0.80449362 ,0.42240349],
 [0.61892953, 0.31949189, 0.83564542, 0.43967919]]
#third value in fifth sublist
xlist[4][2]
#xlist[4,2]


In [ ]:
# First group of array c
print(c[0])

In [ ]:
# Second subgroup of the first group
print(c[0,1])

In [ ]:
# Fourth column of the second subgroup
# print(c[0,1,:,3])

# print(list(c[0,1,:,3]))

#print(c[:,0])

newarr = np.array([[0.6718173948698819, 0.9250566560295915], [0.2662825704884635, 0.19996310250953375]])
print(newarr)


In [ ]:
# Value in the third row and fourth column of the second subgroup of the first group
print(c[0,1,2,3])

In [5]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sum of all elements in matrix a
print(np.sum(a))

In [ ]:
# Sum of each column in matrix a
print(np.sum(a, axis=0))

In [ ]:
# Sum of each row in matrix a
print(np.sum(a, axis=1))

In [ ]:
# Sum of all the elements in the first two groups of array b
np.sum(b[:2])

In [ ]:
# Mean of all elements in matrix a
print(np.mean(a))


In [ ]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))

In [ ]:
# Mean of each row in matrix a
print(np.mean(a, axis=1))

In [ ]:
# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

In [ ]:
x = c[0,0]
print(x)

In [ ]:
y = c[0,1]
print(y)

In [ ]:
# Add elements of x and y together
print(np.add(x, y))

In [ ]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

In [ ]:
# Multiply elements of x and y together
print(np.multiply(x, y))

In [ ]:
# Divide elements of y by elements of x
print(np.divide(x, y))

In [ ]:
print(d)
print(d%2==0)

In [ ]:
%%time
for i in range(100000):
    z = np.multiply(x, y)

In [ ]:
import random
x_list = [[random.random() for j in range(5)] for i in range(4)]
y_list = [[random.random() for j in range(5)] for i in range(4)]

In [ ]:
x_list

In [ ]:
%%time
for i in range(100000):
    z = []
    for i in range(4):
        innerlist = []
        for j in range(5):
            innerlist.append(x_list[i][j]*y_list[i][j])
        z.append(innerlist)

print(z)
    

In [ ]:
%%time
for i in range(100):
    x_new = [j for j in range(1000)]
    

In [ ]:
%%time
for i in range(100):
    x = []
    for j in range(1000):
        x.append(j)
    
#print(x)